import type { Product } from "@/types"
const products: Product[] = [
  {
    id: 1,
    name: 'Portatil',
    maker: 'Asus',
    amount: 10,
    price: 1200000,
    discount: 0,
    id_image: 1,
    description: 'Computador Portátil ASUS Vivobook 16" Pulgadas X1605EA - Intel Core i5 ',
    state: 'Activo',
    image1: 'https://acortar.link/qJG8sb',
    image2: 'https://acortar.link/itQhbY',
    image3: 'https://n9.cl/exzpc',
    image4: 'https://acortar.link/tKOd9r'
  },
  {
    id: 2,
    name: 'Portatil',
    maker: 'HP',
    amount: 12,
    price: 1500000,
    discount: 0,
    id_image: 2,
    description: 'Computador Portátil HP 14" Pulgadas Dq2533la INTEL Core I5',
    state: 'Activo',
    image1: 'https://acortar.link/63g9o8',
    image2: 'https://acortar.link/fKUmd3',
    image3: 'https://n9.cl/u1r6qg',
    image4: 'https://acortar.link/yKrjHy'
  },
  {
    id: 3,
    name: 'Portatil',
    maker: 'Lenovo',
    amount: 10,
    price: 1150000,
    discount: 0,
    id_image: 3,
    description: 'Computador Portátil LENOVO 15,6" Pulgadas IdeaPad Slim 3 - AMD Ryzen 5',
    state: 'Activo',
    image1: 'https://acortar.link/xSEYJg',
    image2: 'https://acortar.link/7O8GGf',
    image3: 'https://acortar.link/HMquGY',
    image4: 'https://acortar.link/ak34JP'
  },
  {
    id: 4,
    name: 'Celular',
    maker: 'Xiomi',
    amount: 15,
    price: 1350000,
    discount: 0,
    id_image: 4,
    description: 'Celular XIAOMI Redmi 12 128GB Color Negro - Bateria de 5000mAh',
    state: 'Activo',
    image1: 'https://acortar.link/azOPt9',
    image2: 'https://acortar.link/JWoTjE',
    image3: 'https://n9.cl/74o78',
    image4: 'https://acortar.link/EkzbvG'
  },
  {
    id: 5,
    name: 'Impresora',
    maker: 'Epson',
    amount: 10,
    price: 750000,
    discount: 0,
    id_image: 5,
    description: 'Multifuncional EPSON Ecotank L3210 Hg - Negro - Wiffi - Red',
    state: 'Activo',
    image1: 'https://n9.cl/45oin',
    image2: 'https://n9.cl/m2cdp',
    image3: 'https://n9.cl/gdw96',
    image4: 'https://n9.cl/4ed7i'
  },
  {
    id: 6,
    name: 'Tablet',
    maker: 'Lenovo',
    amount: 11,
    price: 700000,
    discount: 0,
    id_image: 6,
    description: 'Tablet LENOVO 10" Pulgadas M10 3G Wifi Color Gris 4GB Ram ',
    state: 'Activo',
    image1: 'https://n9.cl/o34trx',
    image2: 'https://n9.cl/g3z8d',
    image3: 'https://n9.cl/yei7s',
    image4: 'https://n9.cl/hnwxm'
  },
  {
    id: 7,
    name: 'Audífonos de Diadema',
    maker: 'JBL',
    amount: 8,
    price: 250000,
    discount: 0,
    id_image: 7,
    description: 'Diadema JBL Alámbricos Gaming Quantum Q100 + cargador',
    state: 'Activo',
    image1: 'https://acortar.link/t31zS4',
    image2: 'https://acortar.link/icqXSU',
    image3: 'https://acortar.link/xc4AA8',
    image4: 'https://n9.cl/udgqb'
  },
  {
    id: 8,
    name: 'Mouse',
    maker: 'HP',
    amount: 7,
    price: 89999,
    discount: 0,
    id_image: 8,
    description: 'Mouse HP Alámbrico Pavilion Gaming 200 Negro - Sensor gamer óptico PixArt de 3200',
    state: 'Activo',
    image1: 'https://n9.cl/8079yl',
    image2: 'https://n9.cl/8jnmhm',
    image3: 'https://n9.cl/7sqjb',
    image4: 'https://n9.cl/3z1jx'
  }
]
export {products}